import { Project, Experience } from './types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'AI A11y',
    client: 'New Relic',
    subtitle: 'Defining accessibility standards for generative AI interfaces.',
    thumbnailUrl: 'https://picsum.photos/id/1/800/600',
    tags: ['AI', 'Accessibility', 'Design System'],
    images: [
      { url: 'https://picsum.photos/id/20/1200/800', caption: 'Screen reader flow for AI-generated code blocks.' },
      { url: 'https://picsum.photos/id/21/1200/800', caption: 'High contrast modes for chat interfaces.' },
    ],
    overview: 'As AI tools become ubiquitous, ensuring they are accessible to all developers is critical. This project established the A11y framework for our AI-assisted features.',
    problemStatement: 'Standard AI chat interfaces often lack semantic structure, making them difficult to navigate for users relying on assistive technology.',
    impact: 'Achieved WCAG 2.1 AA compliance across all new AI features and established a pattern library used by 30+ product teams.',
    scopeAndTeam: 'Lead Designer + Accessibility Specialist. 3 months.',
  },
  {
    id: '2',
    title: 'Contextual AI Patterns',
    client: 'New Relic',
    subtitle: 'Human-centered interaction models for embedded AI.',
    thumbnailUrl: 'https://imgur.com/a/QJDeGfI',
    tags: ['AI', 'UX Patterns', 'Strategy'],
    images: [
      { url: 'https://picsum.photos/id/24/1200/800', caption: 'Context-aware suggestion components.' },
      { url: 'https://picsum.photos/id/25/1200/800', caption: 'Progressive disclosure patterns for AI insights.' },
    ],
    overview: 'Designed, documented, and formalized set of patterns for suggesting next best actions, presenting AI analysis on graphs and charts, and summarizing content.',
    problemStatement: 'Design teams lacked standardized patterns and guidelines for implementing contextual AI features, resulting in inconsistent experiences across products and inefficient design processes, as each team created their own solutions.',
    impact: 'Accelerated development of AI capabilities that differentiate New Relic’s platform, supporting the $100M run-rate target from new products by early 2026.',
    scopeAndTeam: 'Lead Product Designer, collaborating with Experience Design team. 3 months.',
  },
  {
    id: '3',
    title: 'Logs Assistant',
    client: 'New Relic',
    subtitle: 'Querying complex log data with natural language.',
    thumbnailUrl: 'https://pasteboard.co/vT5w2Cz99zN9.png',
    tags: ['Observability', 'AI', 'Data Viz'],
    images: [
      { url: 'https://picsum.photos/id/48/1200/800', caption: 'Natural language query builder.' },
      { url: 'https://picsum.photos/id/49/1200/800', caption: 'Log pattern visualization.' },
    ],
    overview: 'An AI-driven assistant that helps engineers find the needle in the haystack within millions of log lines.',
    problemStatement: 'Mastering proprietary query languages (NRQL) is a high barrier to entry for new engineers, slowing down incident resolution.',
    impact: 'Reduced Mean Time to Resolution (MTTR) by 15% for beta customers. 80% of queries are now initiated via natural language.',
    scopeAndTeam: 'Lead Product Designer. 3 months.',
  },
  {
    id: '4',
    title: 'Self-Service Portal',
    client: 'AWS',
    subtitle: 'Streamlining cloud resource management for enterprise.',
    thumbnailUrl: 'https://gcdnb.pbrd.co/images/g8nyCT5JGlGO.png?o=1',
    tags: ['Cloud', 'Enterprise', 'Dashboard'],
    images: [
      { url: 'https://picsum.photos/id/58/1200/800', caption: 'Unified resource dashboard.' },
      { url: 'https://picsum.photos/id/59/1200/800', caption: 'Cost allocation wizard.' },
    ],
    overview: 'A unified portal allowing enterprise teams to provision and manage AWS resources without navigating the full console complexity.',
    problemStatement: 'Fragmentation across services made it difficult for central IT to maintain governance without becoming a bottleneck.',
    impact: 'Reduced internal support tickets by 30% and improved resource provisioning speed by 4x.',
    scopeAndTeam: 'Senior UX Designer. 3-months.',
  },
  {
    id: '5',
    title: 'Sales Rep Experience',
    client: 'DocuSign',
    subtitle: 'Optimizing the agreement process for mobile sales teams.',
    thumbnailUrl: 'https://pasteboard.co/JDXzDV5IDz7Y.png',
    tags: ['B2B', 'Workflow', 'Mobile'],
    images: [
      { url: 'https://picsum.photos/id/60/1200/800', caption: 'Mobile contract generation flow.' },
    ],
    overview: 'Redesigning the core agreement workflow to enable sales representatives to close deals entirely from their mobile devices.',
    problemStatement: 'The desktop-first experience was cumbersome for field reps, leading to delayed contracts and lost opportunities.',
    impact: '20% increase in mobile-originated contracts and a significant boost in sales rep NPS scores.',
    scopeAndTeam: 'Lead UI/UX Designer. 6 months.',
  },
  {
    id: '6',
    title: 'Finance 360',
    client: 'LinkedIn',
    subtitle: 'Internal financial planning tools for enterprise growth.',
    thumbnailUrl: 'https://pasteboard.co/TyrjpiTIi3VX.png',
    tags: ['Fintech', 'Analytics', 'Enterprise'],
    images: [
      { url: 'https://picsum.photos/id/70/1200/800', caption: 'Budget forecasting module.' },
    ],
    overview: 'A comprehensive dashboard for internal finance teams to track revenue, forecast growth, and manage departmental budgets.',
    problemStatement: 'Reliance on disjointed spreadsheets led to data errors and slow quarterly planning cycles.',
    impact: 'Saved finance teams approximately 10 hours per week per employee during planning seasons.',
    scopeAndTeam: 'Product Designer. 6 months.',
  },
  {
    id: '7',
    title: 'SalesConnect',
    client: 'Cisco Systems',
    subtitle: 'Unified sales enablement and content platform.',
    thumbnailUrl: 'https://pasteboard.co/ShjH8GDgWmCI.png',
    tags: ['Sales', 'CRM', 'Search'],
    images: [
      { url: 'https://picsum.photos/id/80/1200/800', caption: 'Intelligent content search.' },
    ],
    overview: 'Connecting thousands of sales assets with customer data to help reps find the right content at the right time.',
    problemStatement: 'Information silos prevented global sales teams from leveraging high-performing assets.',
    impact: 'Attributed to $50M in revenue influence through better content timing.',
    scopeAndTeam: 'UX Designer. 3 months.',
  },
  {
    id: '8',
    title: 'Conceptual Homepage Redesign',
    client: 'The City of Monterey',
    subtitle: 'Modernizing civic engagement.',
    thumbnailUrl: 'https://pasteboard.co/uRwgPnz03O5Z.png',
    tags: ['Civic Tech', 'Web Design'],
    images: [
      { url: 'https://picsum.photos/id/90/1200/800', caption: 'Desktop homepage concept.' },
    ],
    overview: 'A concept project to reimagine how citizens interact with their local government online.',
    problemStatement: 'The existing site was difficult to navigate and not mobile-responsive.',
    impact: 'Concept work used for portfolio demonstration.',
    scopeAndTeam: 'Personal Project.',
  },
  {
    id: '9',
    title: 'Black History Month 2020',
    client: 'Community',
    subtitle: 'Event branding and digital presence.',
    thumbnailUrl: 'https://pasteboard.co/ixSNQxBO2j7y.png',
    tags: ['Brand Identity', 'Visual Design'],
    images: [
      { url: 'https://picsum.photos/id/100/1200/800', caption: 'Campaign social media assets.' },
    ],
    overview: 'Developing a visual identity for a series of social media banner assets.',
    problemStatement: 'Need for a cohesive look and feel for visual storytelling.',
    impact: 'High social media engagement.',
    scopeAndTeam: 'Personal Project.',
  },
  {
    id: '10',
    title: 'Logo Lab',
    client: 'Various',
    subtitle: 'A collection of identity explorations.',
    thumbnailUrl: 'https://pasteboard.co/sB6KhYCDBJ94.png',
    tags: ['Branding', 'Typography'],
    images: [
      { url: 'https://picsum.photos/id/110/1200/800', caption: 'Logomark sketches and finals.' },
    ],
    overview: 'Experimental branding work and daily logo challenges.',
    problemStatement: 'Exploring form and typography outside of strict client constraints.',
    impact: 'Sharpened visual design skills.',
    scopeAndTeam: 'Personal Project.',
  },
  {
    id: '11',
    title: 'RAW FOODS',
    client: 'Raw Foods Co',
    subtitle: 'Organic e-commerce experience.',
    thumbnailUrl: 'https://pasteboard.co/EPM0N69i7omK.png',
    tags: ['E-commerce', 'Branding'],
    images: [
      { url: 'https://picsum.photos/id/111/1200/800', caption: 'Product detail page.' },
    ],
    overview: 'Direct-to-consumer digital cookbook for healthy and wholesome recipes.',
    problemStatement: 'RAW FOODS needed a digital cookbook with a visual design that matched their "eat clean" brand identity.',
    impact: 'Successful launch and sales.',
    scopeAndTeam: 'Personal Project.',
  },
  {
    id: '12',
    title: 'Yoat: Oat-Based Yogurt',
    client: 'Yoat',
    subtitle: 'Sustainable packaging and web design.',
    thumbnailUrl: 'https://pasteboard.co/UeRsZB2ideX4.png',
    tags: ['Packaging', 'Branding', 'Web'],
    images: [
      { url: 'https://picsum.photos/id/112/1200/800', caption: 'Packaging lineup.' },
    ],
    overview: 'Launching a new plant-based dairy alternative.',
    problemStatement: 'Standing out in a crowded dairy-free market.',
    impact: 'N/A.',
    scopeAndTeam: 'Personal Project.',
  }
];

export const EXPERIENCE: Experience[] = [
  {
    id: '1',
    title: 'Lead Product Designer',
    company: 'New Relic',
    location: 'Los Angeles, CA',
  }
];